apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-config
data:
  telegram_bot_id: "Telegram Bot token"
  spreadsheet_id: "UID of google doc"
  client_secret.json: |
    Insert here service account file content generated in google drive
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: biliardino-bot
  labels:
    app: biliardino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: biliardino
  template:
    metadata:
      labels:
        app: biliardino
    spec:
      containers:
      - name: biliardino
        image: mastrogiovanni/biliardino
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-bot
          mountPath: /etc/credentials/serviceaccount
        env:
          - name: TELEGRAM_BOT_ID
            valueFrom:
              configMapKeyRef:
                name: bot-config
                key: telegram_bot_id
          - name: SPREADSHEET_ID
            valueFrom:
              configMapKeyRef:
                name: bot-config
                key: spreadsheet_id
      volumes:
        - name: config-bot
          configMap:
            name: bot-config
